Feature/auth module
SchweizerischeBundesbahnen/esta-webjs-extensions pull request #2
Opened 2017-06-27 16:33 UTC by kreuzerk

2017-06-29 05:40 UTC, ReToCode requested changes
Siehe Kommentare.

2017-06-29 05:40 UTC, ReToCode commented on src/authentication/authentication.service.ts
> +    static createKeycloak(configUrl) {
Overkill, wenn hier nur eine Zeile ist oder?

2017-06-29 05:40 UTC, ReToCode commented on src/authentication/authentication.service.ts
> +export class EstaAuthService {
Bin mir nicht sicher ob ESTA im Namen wirklich sinnvoll ist. Das sagt ausser uns ja niemandem etwas?

2017-06-29 05:40 UTC, ReToCode commented on src/authentication/authentication.service.ts
> +    public refreshToken(minValidity: number): Promise<boolean> {
Der Parameter könnte optional sein, Default ist ja glaube ich 5s oder so?

2017-06-29 05:40 UTC, ReToCode commented on src/authentication/authentication.module.ts
> +import {EstaAuthService} from './authentication.service';
Authentication != Authorization. Alles (Ordner, Komponente, Modul) sollte nur 'Auth' heissen, da es irgendwann beides machen wird.

2017-06-29 05:40 UTC, ReToCode commented on tslint.json
> +    "directive-selector": [true, "attribute", "esta", "camelCase"],
Auch hier ist esta => wie oben?

2017-06-29 06:09 UTC, kreuzerk commented on src/authentication/authentication.service.ts
> +    static createKeycloak(configUrl) {
Generell ja. Habe das aufgrund des Testings so gemacht. Ich habe es nicht geschafft den Konstruktor Aufruf von Keycloak welches nicht über DI sondern require kommt zu mocken und ein fake Keycloak zurückzugeben. Mit Hilfe dieser Methode kann ich createKeycloak einfach mocken und ein Fake Keycloak Objekt zurückgeben um anschliessend success und error zu testen. Wenn du den Coverage Report anschaust wirst du feststellen das dies die einzige nicht gecoverte Zeile ist. Falls du weisst wie wir das ohne diese Methode lösen können, dann können wir das machen. Ohne diese Methode wäre es mir nicht möglich gewesen die init Methode zu testen.

2017-06-29 06:12 UTC, kreuzerk commented on tslint.json
> +    "directive-selector": [true, "attribute", "esta", "camelCase"],
Einverstanden. Was sollen wir hier setzen? app macht für mich auch keinen Sinn. Oder sollen wir die Checks ganz entfernen?

2017-06-29 06:13 UTC, kreuzerk commented on package.json
> +  "version": "1.1.1",
Stimmt diese Version? Müsste es nach Semantic Versioning 2.0.0 sein?

2017-06-29 09:06 UTC, ReToCode commented on package.json
> +  "version": "1.1.1",
Doch :) Aber da das 1. release nur für uns war, würde ich nicht zu fest verwirren.

2017-06-29 09:07 UTC, ReToCode commented on tslint.json
> +    "directive-selector": [true, "attribute", "esta", "camelCase"],
Ganz entfernen passt.

2017-06-30 11:19 UTC, ReToCode approved these changes

2017-06-30 11:19 UTC, merged